name: Build Windows Executable

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up GHC
      uses: haskell-actions/setup@v2
      with:
        ghc-version: '9.4.8'
        cabal-version: '3.10.2.0'
    
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y mingw-w64 zip
        # Install dependencies for cross-compilation
        bash ./install_deps.sh
    
    - name: Build Windows Executable
      run: |
        # Make the build script executable
        chmod +x ./build-windows.sh
        # Run the build script
        ./build-windows.sh
        
    - name: Create Windows Package
      run: |
        cd dist/windows
        zip -r ../../JustIntonationMusic.zip *
        cd ../..
    
    - name: Build Web Version
      run: |
        # Make the build script executable
        chmod +x ./build-windows-web.sh
        # Build the web version
        ./build-windows-web.sh
        # Copy web version to distribution
        cp ./just-intonation-tracker-web.exe dist/windows/
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: JustIntonationMusic
        path: dist/windows/
        
    - name: Upload ZIP artifact
      uses: actions/upload-artifact@v4
      with:
        name: JustIntonationMusic-ZIP
        path: JustIntonationMusic.zip
